# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: namespace/types.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'namespace/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import enums_pb2 as namespace_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15namespace/types.proto\x12\tnamespace\x1a\x15namespace/enums.proto\"(\n\x04Meta\x12\x10\n\x08root_uid\x18\x01 \x01(\t\x12\x0e\n\x06vendor\x18\x02 \x01(\t\"o\n\x05Value\x12\x17\n\rinteger_value\x18\x01 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x01H\x00\x12\x14\n\ntext_value\x18\x03 \x01(\tH\x00\x12\x17\n\rboolean_value\x18\x04 \x01(\x08H\x00\x42\x07\n\x05typed\"0\n\rOptionalValue\x12\x1f\n\x05value\x18\x01 \x01(\x0b\x32\x10.namespace.Value\"\x82\x01\n\tChildInfo\x12\x10\n\x08\x63hild_id\x18\x01 \x01(\t\x12#\n\x06i_type\x18\x02 \x01(\x0e\x32\x13.namespace.ItemType\x12/\n\nvar_d_type\x18\x03 \x01(\x0e\x32\x16.namespace.VarDataTypeH\x00\x88\x01\x01\x42\r\n\x0b_var_d_type\"\xcd\x02\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x06parent\x18\x03 \x01(\tH\x00\x88\x01\x01\x12/\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\x1d.namespace.Item.ChildrenEntry\x12#\n\x06i_type\x18\x05 \x01(\x0e\x32\x13.namespace.ItemType\x12/\n\nvar_d_type\x18\x06 \x01(\x0e\x32\x16.namespace.VarDataTypeH\x01\x88\x01\x01\x12$\n\x05value\x18\x07 \x01(\x0b\x32\x10.namespace.ValueH\x02\x88\x01\x01\x1a\x45\n\rChildrenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.namespace.ChildInfo:\x02\x38\x01\x42\t\n\x07_parentB\r\n\x0b_var_d_typeB\x08\n\x06_valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'namespace.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM_CHILDRENENTRY']._loaded_options = None
  _globals['_ITEM_CHILDRENENTRY']._serialized_options = b'8\001'
  _globals['_META']._serialized_start=59
  _globals['_META']._serialized_end=99
  _globals['_VALUE']._serialized_start=101
  _globals['_VALUE']._serialized_end=212
  _globals['_OPTIONALVALUE']._serialized_start=214
  _globals['_OPTIONALVALUE']._serialized_end=262
  _globals['_CHILDINFO']._serialized_start=265
  _globals['_CHILDINFO']._serialized_end=395
  _globals['_ITEM']._serialized_start=398
  _globals['_ITEM']._serialized_end=731
  _globals['_ITEM_CHILDRENENTRY']._serialized_start=626
  _globals['_ITEM_CHILDRENENTRY']._serialized_end=695
# @@protoc_insertion_point(module_scope)
