// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: namespace/commands.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  EventType,
  eventTypeFromJSON,
  eventTypeToJSON,
  OperationStatus,
  operationStatusFromJSON,
  operationStatusToJSON,
} from "./enums";
import { FolderInfo, ItemMeta, NamespaceSchema, OptionalValue, VarIdValue, VarInfo } from "./types";

export const protobufPackage = "namespace";

export interface AddCommand {
  cmdId: string;
  parentId?: string | undefined;
  itemsMeta: ItemMeta[];
}

export interface AddResponse {
  cmdId: string;
}

export interface AddBulkCommand {
  cmdId: string;
  parentId: string;
  schema: NamespaceSchema | undefined;
}

export interface AddBulkResponse {
  cmdId: string;
}

export interface ListCommand {
  cmdId: string;
  folderId?: string | undefined;
}

export interface ListResponse {
  cmdId: string;
  folders: FolderInfo[];
  variables: VarInfo[];
}

export interface SetCommand {
  cmdId: string;
  varIdsValues: VarIdValue[];
}

export interface SetResponse {
  cmdId: string;
}

export interface GetCommand {
  cmdId: string;
  varIds: string[];
}

export interface GetResponse {
  cmdId: string;
  varValues: OptionalValue[];
}

export interface SubscribeCommand {
  cmdId: string;
  varIds: string[];
  events: EventType[];
}

export interface SubscribeResponse {
  cmdId: string;
}

export interface UnsubscribeCommand {
  cmdId: string;
  varIds: string[];
  events: EventType[];
}

export interface UnsubscribeResponse {
  cmdId: string;
}

export interface DelCommand {
  cmdId: string;
  itemIds: string[];
}

export interface DelResponse {
  cmdId: string;
}

export interface InvalidCmdResponse {
  cmdId: string;
}

/** Envelopes */
export interface Command {
  add?: AddCommand | undefined;
  list?: ListCommand | undefined;
  set?: SetCommand | undefined;
  get?: GetCommand | undefined;
  del?: DelCommand | undefined;
  addBulk?: AddBulkCommand | undefined;
  sub?: SubscribeCommand | undefined;
  unsub?: UnsubscribeCommand | undefined;
}

export interface Response {
  add?: AddResponse | undefined;
  list?: ListResponse | undefined;
  set?: SetResponse | undefined;
  get?: GetResponse | undefined;
  del?: DelResponse | undefined;
  inv?: InvalidCmdResponse | undefined;
  addBulk?: AddBulkResponse | undefined;
  sub?: SubscribeResponse | undefined;
  unsub?: UnsubscribeResponse | undefined;
  status: OperationStatus;
  errorMsg?: string | undefined;
}

function createBaseAddCommand(): AddCommand {
  return { cmdId: "", parentId: undefined, itemsMeta: [] };
}

export const AddCommand: MessageFns<AddCommand> = {
  encode(message: AddCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    if (message.parentId !== undefined) {
      writer.uint32(18).string(message.parentId);
    }
    for (const v of message.itemsMeta) {
      ItemMeta.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.itemsMeta.push(ItemMeta.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      parentId: isSet(object.parentId)
        ? globalThis.String(object.parentId)
        : isSet(object.parent_id)
        ? globalThis.String(object.parent_id)
        : undefined,
      itemsMeta: globalThis.Array.isArray(object?.itemsMeta)
        ? object.itemsMeta.map((e: any) => ItemMeta.fromJSON(e))
        : globalThis.Array.isArray(object?.items_meta)
        ? object.items_meta.map((e: any) => ItemMeta.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AddCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.parentId !== undefined) {
      obj.parentId = message.parentId;
    }
    if (message.itemsMeta?.length) {
      obj.itemsMeta = message.itemsMeta.map((e) => ItemMeta.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddCommand>, I>>(base?: I): AddCommand {
    return AddCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddCommand>, I>>(object: I): AddCommand {
    const message = createBaseAddCommand();
    message.cmdId = object.cmdId ?? "";
    message.parentId = object.parentId ?? undefined;
    message.itemsMeta = object.itemsMeta?.map((e) => ItemMeta.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddResponse(): AddResponse {
  return { cmdId: "" };
}

export const AddResponse: MessageFns<AddResponse> = {
  encode(message: AddResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: AddResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddResponse>, I>>(base?: I): AddResponse {
    return AddResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddResponse>, I>>(object: I): AddResponse {
    const message = createBaseAddResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseAddBulkCommand(): AddBulkCommand {
  return { cmdId: "", parentId: "", schema: undefined };
}

export const AddBulkCommand: MessageFns<AddBulkCommand> = {
  encode(message: AddBulkCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    if (message.parentId !== "") {
      writer.uint32(18).string(message.parentId);
    }
    if (message.schema !== undefined) {
      NamespaceSchema.encode(message.schema, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddBulkCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddBulkCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.schema = NamespaceSchema.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddBulkCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      parentId: isSet(object.parentId)
        ? globalThis.String(object.parentId)
        : isSet(object.parent_id)
        ? globalThis.String(object.parent_id)
        : "",
      schema: isSet(object.schema) ? NamespaceSchema.fromJSON(object.schema) : undefined,
    };
  },

  toJSON(message: AddBulkCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.parentId !== "") {
      obj.parentId = message.parentId;
    }
    if (message.schema !== undefined) {
      obj.schema = NamespaceSchema.toJSON(message.schema);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddBulkCommand>, I>>(base?: I): AddBulkCommand {
    return AddBulkCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddBulkCommand>, I>>(object: I): AddBulkCommand {
    const message = createBaseAddBulkCommand();
    message.cmdId = object.cmdId ?? "";
    message.parentId = object.parentId ?? "";
    message.schema = (object.schema !== undefined && object.schema !== null)
      ? NamespaceSchema.fromPartial(object.schema)
      : undefined;
    return message;
  },
};

function createBaseAddBulkResponse(): AddBulkResponse {
  return { cmdId: "" };
}

export const AddBulkResponse: MessageFns<AddBulkResponse> = {
  encode(message: AddBulkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddBulkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddBulkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddBulkResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: AddBulkResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddBulkResponse>, I>>(base?: I): AddBulkResponse {
    return AddBulkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddBulkResponse>, I>>(object: I): AddBulkResponse {
    const message = createBaseAddBulkResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseListCommand(): ListCommand {
  return { cmdId: "", folderId: undefined };
}

export const ListCommand: MessageFns<ListCommand> = {
  encode(message: ListCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    if (message.folderId !== undefined) {
      writer.uint32(18).string(message.folderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folderId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      folderId: isSet(object.folderId)
        ? globalThis.String(object.folderId)
        : isSet(object.folder_id)
        ? globalThis.String(object.folder_id)
        : undefined,
    };
  },

  toJSON(message: ListCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.folderId !== undefined) {
      obj.folderId = message.folderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCommand>, I>>(base?: I): ListCommand {
    return ListCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCommand>, I>>(object: I): ListCommand {
    const message = createBaseListCommand();
    message.cmdId = object.cmdId ?? "";
    message.folderId = object.folderId ?? undefined;
    return message;
  },
};

function createBaseListResponse(): ListResponse {
  return { cmdId: "", folders: [], variables: [] };
}

export const ListResponse: MessageFns<ListResponse> = {
  encode(message: ListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.folders) {
      FolderInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.variables) {
      VarInfo.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folders.push(FolderInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.variables.push(VarInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      folders: globalThis.Array.isArray(object?.folders) ? object.folders.map((e: any) => FolderInfo.fromJSON(e)) : [],
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => VarInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.folders?.length) {
      obj.folders = message.folders.map((e) => FolderInfo.toJSON(e));
    }
    if (message.variables?.length) {
      obj.variables = message.variables.map((e) => VarInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListResponse>, I>>(base?: I): ListResponse {
    return ListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListResponse>, I>>(object: I): ListResponse {
    const message = createBaseListResponse();
    message.cmdId = object.cmdId ?? "";
    message.folders = object.folders?.map((e) => FolderInfo.fromPartial(e)) || [];
    message.variables = object.variables?.map((e) => VarInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSetCommand(): SetCommand {
  return { cmdId: "", varIdsValues: [] };
}

export const SetCommand: MessageFns<SetCommand> = {
  encode(message: SetCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varIdsValues) {
      VarIdValue.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varIdsValues.push(VarIdValue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      varIdsValues: globalThis.Array.isArray(object?.varIdsValues)
        ? object.varIdsValues.map((e: any) => VarIdValue.fromJSON(e))
        : globalThis.Array.isArray(object?.var_ids_values)
        ? object.var_ids_values.map((e: any) => VarIdValue.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SetCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varIdsValues?.length) {
      obj.varIdsValues = message.varIdsValues.map((e) => VarIdValue.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetCommand>, I>>(base?: I): SetCommand {
    return SetCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetCommand>, I>>(object: I): SetCommand {
    const message = createBaseSetCommand();
    message.cmdId = object.cmdId ?? "";
    message.varIdsValues = object.varIdsValues?.map((e) => VarIdValue.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSetResponse(): SetResponse {
  return { cmdId: "" };
}

export const SetResponse: MessageFns<SetResponse> = {
  encode(message: SetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: SetResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetResponse>, I>>(base?: I): SetResponse {
    return SetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetResponse>, I>>(object: I): SetResponse {
    const message = createBaseSetResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseGetCommand(): GetCommand {
  return { cmdId: "", varIds: [] };
}

export const GetCommand: MessageFns<GetCommand> = {
  encode(message: GetCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      varIds: globalThis.Array.isArray(object?.varIds)
        ? object.varIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.var_ids)
        ? object.var_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: GetCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varIds?.length) {
      obj.varIds = message.varIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCommand>, I>>(base?: I): GetCommand {
    return GetCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCommand>, I>>(object: I): GetCommand {
    const message = createBaseGetCommand();
    message.cmdId = object.cmdId ?? "";
    message.varIds = object.varIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetResponse(): GetResponse {
  return { cmdId: "", varValues: [] };
}

export const GetResponse: MessageFns<GetResponse> = {
  encode(message: GetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varValues) {
      OptionalValue.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varValues.push(OptionalValue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      varValues: globalThis.Array.isArray(object?.varValues)
        ? object.varValues.map((e: any) => OptionalValue.fromJSON(e))
        : globalThis.Array.isArray(object?.var_values)
        ? object.var_values.map((e: any) => OptionalValue.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varValues?.length) {
      obj.varValues = message.varValues.map((e) => OptionalValue.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetResponse>, I>>(base?: I): GetResponse {
    return GetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetResponse>, I>>(object: I): GetResponse {
    const message = createBaseGetResponse();
    message.cmdId = object.cmdId ?? "";
    message.varValues = object.varValues?.map((e) => OptionalValue.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSubscribeCommand(): SubscribeCommand {
  return { cmdId: "", varIds: [], events: [] };
}

export const SubscribeCommand: MessageFns<SubscribeCommand> = {
  encode(message: SubscribeCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varIds) {
      writer.uint32(18).string(v!);
    }
    writer.uint32(26).fork();
    for (const v of message.events) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varIds.push(reader.string());
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.events.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.events.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      varIds: globalThis.Array.isArray(object?.varIds)
        ? object.varIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.var_ids)
        ? object.var_ids.map((e: any) => globalThis.String(e))
        : [],
      events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => eventTypeFromJSON(e)) : [],
    };
  },

  toJSON(message: SubscribeCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varIds?.length) {
      obj.varIds = message.varIds;
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => eventTypeToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeCommand>, I>>(base?: I): SubscribeCommand {
    return SubscribeCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeCommand>, I>>(object: I): SubscribeCommand {
    const message = createBaseSubscribeCommand();
    message.cmdId = object.cmdId ?? "";
    message.varIds = object.varIds?.map((e) => e) || [];
    message.events = object.events?.map((e) => e) || [];
    return message;
  },
};

function createBaseSubscribeResponse(): SubscribeResponse {
  return { cmdId: "" };
}

export const SubscribeResponse: MessageFns<SubscribeResponse> = {
  encode(message: SubscribeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: SubscribeResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeResponse>, I>>(base?: I): SubscribeResponse {
    return SubscribeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeResponse>, I>>(object: I): SubscribeResponse {
    const message = createBaseSubscribeResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseUnsubscribeCommand(): UnsubscribeCommand {
  return { cmdId: "", varIds: [], events: [] };
}

export const UnsubscribeCommand: MessageFns<UnsubscribeCommand> = {
  encode(message: UnsubscribeCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varIds) {
      writer.uint32(18).string(v!);
    }
    writer.uint32(26).fork();
    for (const v of message.events) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnsubscribeCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnsubscribeCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varIds.push(reader.string());
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.events.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.events.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnsubscribeCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      varIds: globalThis.Array.isArray(object?.varIds)
        ? object.varIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.var_ids)
        ? object.var_ids.map((e: any) => globalThis.String(e))
        : [],
      events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => eventTypeFromJSON(e)) : [],
    };
  },

  toJSON(message: UnsubscribeCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varIds?.length) {
      obj.varIds = message.varIds;
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => eventTypeToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnsubscribeCommand>, I>>(base?: I): UnsubscribeCommand {
    return UnsubscribeCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnsubscribeCommand>, I>>(object: I): UnsubscribeCommand {
    const message = createBaseUnsubscribeCommand();
    message.cmdId = object.cmdId ?? "";
    message.varIds = object.varIds?.map((e) => e) || [];
    message.events = object.events?.map((e) => e) || [];
    return message;
  },
};

function createBaseUnsubscribeResponse(): UnsubscribeResponse {
  return { cmdId: "" };
}

export const UnsubscribeResponse: MessageFns<UnsubscribeResponse> = {
  encode(message: UnsubscribeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnsubscribeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnsubscribeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnsubscribeResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: UnsubscribeResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnsubscribeResponse>, I>>(base?: I): UnsubscribeResponse {
    return UnsubscribeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnsubscribeResponse>, I>>(object: I): UnsubscribeResponse {
    const message = createBaseUnsubscribeResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseDelCommand(): DelCommand {
  return { cmdId: "", itemIds: [] };
}

export const DelCommand: MessageFns<DelCommand> = {
  encode(message: DelCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.itemIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DelCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDelCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.itemIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DelCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
      itemIds: globalThis.Array.isArray(object?.itemIds)
        ? object.itemIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.item_ids)
        ? object.item_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: DelCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.itemIds?.length) {
      obj.itemIds = message.itemIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DelCommand>, I>>(base?: I): DelCommand {
    return DelCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DelCommand>, I>>(object: I): DelCommand {
    const message = createBaseDelCommand();
    message.cmdId = object.cmdId ?? "";
    message.itemIds = object.itemIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseDelResponse(): DelResponse {
  return { cmdId: "" };
}

export const DelResponse: MessageFns<DelResponse> = {
  encode(message: DelResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DelResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DelResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: DelResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DelResponse>, I>>(base?: I): DelResponse {
    return DelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DelResponse>, I>>(object: I): DelResponse {
    const message = createBaseDelResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseInvalidCmdResponse(): InvalidCmdResponse {
  return { cmdId: "" };
}

export const InvalidCmdResponse: MessageFns<InvalidCmdResponse> = {
  encode(message: InvalidCmdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvalidCmdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvalidCmdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InvalidCmdResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
        ? globalThis.String(object.cmd_id)
        : "",
    };
  },

  toJSON(message: InvalidCmdResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvalidCmdResponse>, I>>(base?: I): InvalidCmdResponse {
    return InvalidCmdResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvalidCmdResponse>, I>>(object: I): InvalidCmdResponse {
    const message = createBaseInvalidCmdResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseCommand(): Command {
  return {
    add: undefined,
    list: undefined,
    set: undefined,
    get: undefined,
    del: undefined,
    addBulk: undefined,
    sub: undefined,
    unsub: undefined,
  };
}

export const Command: MessageFns<Command> = {
  encode(message: Command, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.add !== undefined) {
      AddCommand.encode(message.add, writer.uint32(10).fork()).join();
    }
    if (message.list !== undefined) {
      ListCommand.encode(message.list, writer.uint32(18).fork()).join();
    }
    if (message.set !== undefined) {
      SetCommand.encode(message.set, writer.uint32(26).fork()).join();
    }
    if (message.get !== undefined) {
      GetCommand.encode(message.get, writer.uint32(34).fork()).join();
    }
    if (message.del !== undefined) {
      DelCommand.encode(message.del, writer.uint32(42).fork()).join();
    }
    if (message.addBulk !== undefined) {
      AddBulkCommand.encode(message.addBulk, writer.uint32(50).fork()).join();
    }
    if (message.sub !== undefined) {
      SubscribeCommand.encode(message.sub, writer.uint32(58).fork()).join();
    }
    if (message.unsub !== undefined) {
      UnsubscribeCommand.encode(message.unsub, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Command {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.add = AddCommand.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.list = ListCommand.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.set = SetCommand.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.get = GetCommand.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.del = DelCommand.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.addBulk = AddBulkCommand.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sub = SubscribeCommand.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.unsub = UnsubscribeCommand.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Command {
    return {
      add: isSet(object.add) ? AddCommand.fromJSON(object.add) : undefined,
      list: isSet(object.list) ? ListCommand.fromJSON(object.list) : undefined,
      set: isSet(object.set) ? SetCommand.fromJSON(object.set) : undefined,
      get: isSet(object.get) ? GetCommand.fromJSON(object.get) : undefined,
      del: isSet(object.del) ? DelCommand.fromJSON(object.del) : undefined,
      addBulk: isSet(object.addBulk)
        ? AddBulkCommand.fromJSON(object.addBulk)
        : isSet(object.add_bulk)
        ? AddBulkCommand.fromJSON(object.add_bulk)
        : undefined,
      sub: isSet(object.sub) ? SubscribeCommand.fromJSON(object.sub) : undefined,
      unsub: isSet(object.unsub) ? UnsubscribeCommand.fromJSON(object.unsub) : undefined,
    };
  },

  toJSON(message: Command): unknown {
    const obj: any = {};
    if (message.add !== undefined) {
      obj.add = AddCommand.toJSON(message.add);
    }
    if (message.list !== undefined) {
      obj.list = ListCommand.toJSON(message.list);
    }
    if (message.set !== undefined) {
      obj.set = SetCommand.toJSON(message.set);
    }
    if (message.get !== undefined) {
      obj.get = GetCommand.toJSON(message.get);
    }
    if (message.del !== undefined) {
      obj.del = DelCommand.toJSON(message.del);
    }
    if (message.addBulk !== undefined) {
      obj.addBulk = AddBulkCommand.toJSON(message.addBulk);
    }
    if (message.sub !== undefined) {
      obj.sub = SubscribeCommand.toJSON(message.sub);
    }
    if (message.unsub !== undefined) {
      obj.unsub = UnsubscribeCommand.toJSON(message.unsub);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Command>, I>>(base?: I): Command {
    return Command.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Command>, I>>(object: I): Command {
    const message = createBaseCommand();
    message.add = (object.add !== undefined && object.add !== null) ? AddCommand.fromPartial(object.add) : undefined;
    message.list = (object.list !== undefined && object.list !== null)
      ? ListCommand.fromPartial(object.list)
      : undefined;
    message.set = (object.set !== undefined && object.set !== null) ? SetCommand.fromPartial(object.set) : undefined;
    message.get = (object.get !== undefined && object.get !== null) ? GetCommand.fromPartial(object.get) : undefined;
    message.del = (object.del !== undefined && object.del !== null) ? DelCommand.fromPartial(object.del) : undefined;
    message.addBulk = (object.addBulk !== undefined && object.addBulk !== null)
      ? AddBulkCommand.fromPartial(object.addBulk)
      : undefined;
    message.sub = (object.sub !== undefined && object.sub !== null)
      ? SubscribeCommand.fromPartial(object.sub)
      : undefined;
    message.unsub = (object.unsub !== undefined && object.unsub !== null)
      ? UnsubscribeCommand.fromPartial(object.unsub)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    add: undefined,
    list: undefined,
    set: undefined,
    get: undefined,
    del: undefined,
    inv: undefined,
    addBulk: undefined,
    sub: undefined,
    unsub: undefined,
    status: 0,
    errorMsg: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.add !== undefined) {
      AddResponse.encode(message.add, writer.uint32(10).fork()).join();
    }
    if (message.list !== undefined) {
      ListResponse.encode(message.list, writer.uint32(18).fork()).join();
    }
    if (message.set !== undefined) {
      SetResponse.encode(message.set, writer.uint32(26).fork()).join();
    }
    if (message.get !== undefined) {
      GetResponse.encode(message.get, writer.uint32(34).fork()).join();
    }
    if (message.del !== undefined) {
      DelResponse.encode(message.del, writer.uint32(42).fork()).join();
    }
    if (message.inv !== undefined) {
      InvalidCmdResponse.encode(message.inv, writer.uint32(50).fork()).join();
    }
    if (message.addBulk !== undefined) {
      AddBulkResponse.encode(message.addBulk, writer.uint32(58).fork()).join();
    }
    if (message.sub !== undefined) {
      SubscribeResponse.encode(message.sub, writer.uint32(66).fork()).join();
    }
    if (message.unsub !== undefined) {
      UnsubscribeResponse.encode(message.unsub, writer.uint32(74).fork()).join();
    }
    if (message.status !== 0) {
      writer.uint32(80).int32(message.status);
    }
    if (message.errorMsg !== undefined) {
      writer.uint32(90).string(message.errorMsg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.add = AddResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.list = ListResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.set = SetResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.get = GetResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.del = DelResponse.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.inv = InvalidCmdResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.addBulk = AddBulkResponse.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.sub = SubscribeResponse.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.unsub = UnsubscribeResponse.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.errorMsg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      add: isSet(object.add) ? AddResponse.fromJSON(object.add) : undefined,
      list: isSet(object.list) ? ListResponse.fromJSON(object.list) : undefined,
      set: isSet(object.set) ? SetResponse.fromJSON(object.set) : undefined,
      get: isSet(object.get) ? GetResponse.fromJSON(object.get) : undefined,
      del: isSet(object.del) ? DelResponse.fromJSON(object.del) : undefined,
      inv: isSet(object.inv) ? InvalidCmdResponse.fromJSON(object.inv) : undefined,
      addBulk: isSet(object.addBulk)
        ? AddBulkResponse.fromJSON(object.addBulk)
        : isSet(object.add_bulk)
        ? AddBulkResponse.fromJSON(object.add_bulk)
        : undefined,
      sub: isSet(object.sub) ? SubscribeResponse.fromJSON(object.sub) : undefined,
      unsub: isSet(object.unsub) ? UnsubscribeResponse.fromJSON(object.unsub) : undefined,
      status: isSet(object.status) ? operationStatusFromJSON(object.status) : 0,
      errorMsg: isSet(object.errorMsg)
        ? globalThis.String(object.errorMsg)
        : isSet(object.error_msg)
        ? globalThis.String(object.error_msg)
        : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.add !== undefined) {
      obj.add = AddResponse.toJSON(message.add);
    }
    if (message.list !== undefined) {
      obj.list = ListResponse.toJSON(message.list);
    }
    if (message.set !== undefined) {
      obj.set = SetResponse.toJSON(message.set);
    }
    if (message.get !== undefined) {
      obj.get = GetResponse.toJSON(message.get);
    }
    if (message.del !== undefined) {
      obj.del = DelResponse.toJSON(message.del);
    }
    if (message.inv !== undefined) {
      obj.inv = InvalidCmdResponse.toJSON(message.inv);
    }
    if (message.addBulk !== undefined) {
      obj.addBulk = AddBulkResponse.toJSON(message.addBulk);
    }
    if (message.sub !== undefined) {
      obj.sub = SubscribeResponse.toJSON(message.sub);
    }
    if (message.unsub !== undefined) {
      obj.unsub = UnsubscribeResponse.toJSON(message.unsub);
    }
    if (message.status !== 0) {
      obj.status = operationStatusToJSON(message.status);
    }
    if (message.errorMsg !== undefined) {
      obj.errorMsg = message.errorMsg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.add = (object.add !== undefined && object.add !== null) ? AddResponse.fromPartial(object.add) : undefined;
    message.list = (object.list !== undefined && object.list !== null)
      ? ListResponse.fromPartial(object.list)
      : undefined;
    message.set = (object.set !== undefined && object.set !== null) ? SetResponse.fromPartial(object.set) : undefined;
    message.get = (object.get !== undefined && object.get !== null) ? GetResponse.fromPartial(object.get) : undefined;
    message.del = (object.del !== undefined && object.del !== null) ? DelResponse.fromPartial(object.del) : undefined;
    message.inv = (object.inv !== undefined && object.inv !== null)
      ? InvalidCmdResponse.fromPartial(object.inv)
      : undefined;
    message.addBulk = (object.addBulk !== undefined && object.addBulk !== null)
      ? AddBulkResponse.fromPartial(object.addBulk)
      : undefined;
    message.sub = (object.sub !== undefined && object.sub !== null)
      ? SubscribeResponse.fromPartial(object.sub)
      : undefined;
    message.unsub = (object.unsub !== undefined && object.unsub !== null)
      ? UnsubscribeResponse.fromPartial(object.unsub)
      : undefined;
    message.status = object.status ?? 0;
    message.errorMsg = object.errorMsg ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
