// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: namespace/commands.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  ItemType,
  itemTypeFromJSON,
  itemTypeToJSON,
  OperationStatus,
  operationStatusFromJSON,
  operationStatusToJSON,
  VarDataType,
  varDataTypeFromJSON,
  varDataTypeToJSON,
} from "./enums";
import { NamespaceSchema, OptionalValue, Value } from "./types";

export const protobufPackage = "namespace";

export interface ItemMeta {
  name: string;
  iType: ItemType;
  varDType?: VarDataType | undefined;
  uid?: string | undefined;
}

export interface VarInfo {
  varId: string;
  varDType: VarDataType;
}

export interface VarIdValue {
  varId: string;
  value: Value | undefined;
}

export interface AddCommand {
  cmdId: string;
  parentId: string;
  itemsMeta: ItemMeta[];
}

export interface AddResponse {
  cmdId: string;
  itemIds: string[];
}

export interface AddBulkCommand {
  cmdId: string;
  parentId: string;
  schema: NamespaceSchema | undefined;
}

export interface AddBulkResponse {
  cmdId: string;
}

export interface ListCommand {
  cmdId: string;
  folderId?: string | undefined;
}

export interface ListResponse {
  cmdId: string;
  childrenFolders: { [key: string]: string };
  childrenVars: { [key: string]: VarInfo };
}

export interface ListResponse_ChildrenFoldersEntry {
  key: string;
  value: string;
}

export interface ListResponse_ChildrenVarsEntry {
  key: string;
  value: VarInfo | undefined;
}

export interface SetCommand {
  cmdId: string;
  varIdsValues: VarIdValue[];
}

export interface SetResponse {
  cmdId: string;
}

export interface GetCommand {
  cmdId: string;
  varIds: string[];
}

export interface GetResponse {
  cmdId: string;
  varValues: OptionalValue[];
}

export interface DelCommand {
  cmdId: string;
  itemIds: string[];
}

export interface DelResponse {
  cmdId: string;
}

export interface InvalidCmdResponse {
  cmdId: string;
}

/** Envelopes */
export interface Command {
  add?: AddCommand | undefined;
  list?: ListCommand | undefined;
  set?: SetCommand | undefined;
  get?: GetCommand | undefined;
  del?: DelCommand | undefined;
  addBulk?: AddBulkCommand | undefined;
}

export interface Response {
  add?: AddResponse | undefined;
  list?: ListResponse | undefined;
  set?: SetResponse | undefined;
  get?: GetResponse | undefined;
  del?: DelResponse | undefined;
  inv?: InvalidCmdResponse | undefined;
  addBulk?: AddBulkResponse | undefined;
  status: OperationStatus;
  errorMsg?: string | undefined;
}

function createBaseItemMeta(): ItemMeta {
  return { name: "", iType: 0, varDType: undefined, uid: undefined };
}

export const ItemMeta: MessageFns<ItemMeta> = {
  encode(
    message: ItemMeta,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.iType !== 0) {
      writer.uint32(16).int32(message.iType);
    }
    if (message.varDType !== undefined) {
      writer.uint32(24).int32(message.varDType);
    }
    if (message.uid !== undefined) {
      writer.uint32(34).string(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemMeta {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemMeta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.iType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.varDType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemMeta {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      iType: isSet(object.iType)
        ? itemTypeFromJSON(object.iType)
        : isSet(object.i_type)
          ? itemTypeFromJSON(object.i_type)
          : 0,
      varDType: isSet(object.varDType)
        ? varDataTypeFromJSON(object.varDType)
        : isSet(object.var_d_type)
          ? varDataTypeFromJSON(object.var_d_type)
          : undefined,
      uid: isSet(object.uid) ? globalThis.String(object.uid) : undefined,
    };
  },

  toJSON(message: ItemMeta): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.iType !== 0) {
      obj.iType = itemTypeToJSON(message.iType);
    }
    if (message.varDType !== undefined) {
      obj.varDType = varDataTypeToJSON(message.varDType);
    }
    if (message.uid !== undefined) {
      obj.uid = message.uid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemMeta>, I>>(base?: I): ItemMeta {
    return ItemMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemMeta>, I>>(object: I): ItemMeta {
    const message = createBaseItemMeta();
    message.name = object.name ?? "";
    message.iType = object.iType ?? 0;
    message.varDType = object.varDType ?? undefined;
    message.uid = object.uid ?? undefined;
    return message;
  },
};

function createBaseVarInfo(): VarInfo {
  return { varId: "", varDType: 0 };
}

export const VarInfo: MessageFns<VarInfo> = {
  encode(
    message: VarInfo,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.varId !== "") {
      writer.uint32(10).string(message.varId);
    }
    if (message.varDType !== 0) {
      writer.uint32(16).int32(message.varDType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VarInfo {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVarInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.varId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.varDType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VarInfo {
    return {
      varId: isSet(object.varId)
        ? globalThis.String(object.varId)
        : isSet(object.var_id)
          ? globalThis.String(object.var_id)
          : "",
      varDType: isSet(object.varDType)
        ? varDataTypeFromJSON(object.varDType)
        : isSet(object.var_d_type)
          ? varDataTypeFromJSON(object.var_d_type)
          : 0,
    };
  },

  toJSON(message: VarInfo): unknown {
    const obj: any = {};
    if (message.varId !== "") {
      obj.varId = message.varId;
    }
    if (message.varDType !== 0) {
      obj.varDType = varDataTypeToJSON(message.varDType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VarInfo>, I>>(base?: I): VarInfo {
    return VarInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VarInfo>, I>>(object: I): VarInfo {
    const message = createBaseVarInfo();
    message.varId = object.varId ?? "";
    message.varDType = object.varDType ?? 0;
    return message;
  },
};

function createBaseVarIdValue(): VarIdValue {
  return { varId: "", value: undefined };
}

export const VarIdValue: MessageFns<VarIdValue> = {
  encode(
    message: VarIdValue,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.varId !== "") {
      writer.uint32(10).string(message.varId);
    }
    if (message.value !== undefined) {
      Value.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VarIdValue {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVarIdValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.varId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Value.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VarIdValue {
    return {
      varId: isSet(object.varId)
        ? globalThis.String(object.varId)
        : isSet(object.var_id)
          ? globalThis.String(object.var_id)
          : "",
      value: isSet(object.value) ? Value.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: VarIdValue): unknown {
    const obj: any = {};
    if (message.varId !== "") {
      obj.varId = message.varId;
    }
    if (message.value !== undefined) {
      obj.value = Value.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VarIdValue>, I>>(base?: I): VarIdValue {
    return VarIdValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VarIdValue>, I>>(
    object: I,
  ): VarIdValue {
    const message = createBaseVarIdValue();
    message.varId = object.varId ?? "";
    message.value =
      object.value !== undefined && object.value !== null
        ? Value.fromPartial(object.value)
        : undefined;
    return message;
  },
};

function createBaseAddCommand(): AddCommand {
  return { cmdId: "", parentId: "", itemsMeta: [] };
}

export const AddCommand: MessageFns<AddCommand> = {
  encode(
    message: AddCommand,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    if (message.parentId !== "") {
      writer.uint32(18).string(message.parentId);
    }
    for (const v of message.itemsMeta) {
      ItemMeta.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddCommand {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.itemsMeta.push(ItemMeta.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      parentId: isSet(object.parentId)
        ? globalThis.String(object.parentId)
        : isSet(object.parent_id)
          ? globalThis.String(object.parent_id)
          : "",
      itemsMeta: globalThis.Array.isArray(object?.itemsMeta)
        ? object.itemsMeta.map((e: any) => ItemMeta.fromJSON(e))
        : globalThis.Array.isArray(object?.items_meta)
          ? object.items_meta.map((e: any) => ItemMeta.fromJSON(e))
          : [],
    };
  },

  toJSON(message: AddCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.parentId !== "") {
      obj.parentId = message.parentId;
    }
    if (message.itemsMeta?.length) {
      obj.itemsMeta = message.itemsMeta.map((e) => ItemMeta.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddCommand>, I>>(base?: I): AddCommand {
    return AddCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddCommand>, I>>(
    object: I,
  ): AddCommand {
    const message = createBaseAddCommand();
    message.cmdId = object.cmdId ?? "";
    message.parentId = object.parentId ?? "";
    message.itemsMeta =
      object.itemsMeta?.map((e) => ItemMeta.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddResponse(): AddResponse {
  return { cmdId: "", itemIds: [] };
}

export const AddResponse: MessageFns<AddResponse> = {
  encode(
    message: AddResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.itemIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.itemIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      itemIds: globalThis.Array.isArray(object?.itemIds)
        ? object.itemIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.item_ids)
          ? object.item_ids.map((e: any) => globalThis.String(e))
          : [],
    };
  },

  toJSON(message: AddResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.itemIds?.length) {
      obj.itemIds = message.itemIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddResponse>, I>>(base?: I): AddResponse {
    return AddResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddResponse>, I>>(
    object: I,
  ): AddResponse {
    const message = createBaseAddResponse();
    message.cmdId = object.cmdId ?? "";
    message.itemIds = object.itemIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseAddBulkCommand(): AddBulkCommand {
  return { cmdId: "", parentId: "", schema: undefined };
}

export const AddBulkCommand: MessageFns<AddBulkCommand> = {
  encode(
    message: AddBulkCommand,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    if (message.parentId !== "") {
      writer.uint32(18).string(message.parentId);
    }
    if (message.schema !== undefined) {
      NamespaceSchema.encode(message.schema, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddBulkCommand {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddBulkCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.schema = NamespaceSchema.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddBulkCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      parentId: isSet(object.parentId)
        ? globalThis.String(object.parentId)
        : isSet(object.parent_id)
          ? globalThis.String(object.parent_id)
          : "",
      schema: isSet(object.schema)
        ? NamespaceSchema.fromJSON(object.schema)
        : undefined,
    };
  },

  toJSON(message: AddBulkCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.parentId !== "") {
      obj.parentId = message.parentId;
    }
    if (message.schema !== undefined) {
      obj.schema = NamespaceSchema.toJSON(message.schema);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddBulkCommand>, I>>(
    base?: I,
  ): AddBulkCommand {
    return AddBulkCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddBulkCommand>, I>>(
    object: I,
  ): AddBulkCommand {
    const message = createBaseAddBulkCommand();
    message.cmdId = object.cmdId ?? "";
    message.parentId = object.parentId ?? "";
    message.schema =
      object.schema !== undefined && object.schema !== null
        ? NamespaceSchema.fromPartial(object.schema)
        : undefined;
    return message;
  },
};

function createBaseAddBulkResponse(): AddBulkResponse {
  return { cmdId: "" };
}

export const AddBulkResponse: MessageFns<AddBulkResponse> = {
  encode(
    message: AddBulkResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddBulkResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddBulkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddBulkResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
    };
  },

  toJSON(message: AddBulkResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddBulkResponse>, I>>(
    base?: I,
  ): AddBulkResponse {
    return AddBulkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddBulkResponse>, I>>(
    object: I,
  ): AddBulkResponse {
    const message = createBaseAddBulkResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseListCommand(): ListCommand {
  return { cmdId: "", folderId: undefined };
}

export const ListCommand: MessageFns<ListCommand> = {
  encode(
    message: ListCommand,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    if (message.folderId !== undefined) {
      writer.uint32(18).string(message.folderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCommand {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folderId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      folderId: isSet(object.folderId)
        ? globalThis.String(object.folderId)
        : isSet(object.folder_id)
          ? globalThis.String(object.folder_id)
          : undefined,
    };
  },

  toJSON(message: ListCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.folderId !== undefined) {
      obj.folderId = message.folderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCommand>, I>>(base?: I): ListCommand {
    return ListCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCommand>, I>>(
    object: I,
  ): ListCommand {
    const message = createBaseListCommand();
    message.cmdId = object.cmdId ?? "";
    message.folderId = object.folderId ?? undefined;
    return message;
  },
};

function createBaseListResponse(): ListResponse {
  return { cmdId: "", childrenFolders: {}, childrenVars: {} };
}

export const ListResponse: MessageFns<ListResponse> = {
  encode(
    message: ListResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    globalThis.Object.entries(message.childrenFolders).forEach(
      ([key, value]: [string, string]) => {
        ListResponse_ChildrenFoldersEntry.encode(
          { key: key as any, value },
          writer.uint32(18).fork(),
        ).join();
      },
    );
    globalThis.Object.entries(message.childrenVars).forEach(
      ([key, value]: [string, VarInfo]) => {
        ListResponse_ChildrenVarsEntry.encode(
          { key: key as any, value },
          writer.uint32(26).fork(),
        ).join();
      },
    );
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = ListResponse_ChildrenFoldersEntry.decode(
            reader,
            reader.uint32(),
          );
          if (entry2.value !== undefined) {
            message.childrenFolders[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = ListResponse_ChildrenVarsEntry.decode(
            reader,
            reader.uint32(),
          );
          if (entry3.value !== undefined) {
            message.childrenVars[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      childrenFolders: isObject(object.childrenFolders)
        ? (
            globalThis.Object.entries(object.childrenFolders) as [string, any][]
          ).reduce(
            (acc: { [key: string]: string }, [key, value]: [string, any]) => {
              acc[key] = globalThis.String(value);
              return acc;
            },
            {},
          )
        : isObject(object.children_folders)
          ? (
              globalThis.Object.entries(object.children_folders) as [
                string,
                any,
              ][]
            ).reduce(
              (acc: { [key: string]: string }, [key, value]: [string, any]) => {
                acc[key] = globalThis.String(value);
                return acc;
              },
              {},
            )
          : {},
      childrenVars: isObject(object.childrenVars)
        ? (
            globalThis.Object.entries(object.childrenVars) as [string, any][]
          ).reduce(
            (acc: { [key: string]: VarInfo }, [key, value]: [string, any]) => {
              acc[key] = VarInfo.fromJSON(value);
              return acc;
            },
            {},
          )
        : isObject(object.children_vars)
          ? (
              globalThis.Object.entries(object.children_vars) as [string, any][]
            ).reduce(
              (
                acc: { [key: string]: VarInfo },
                [key, value]: [string, any],
              ) => {
                acc[key] = VarInfo.fromJSON(value);
                return acc;
              },
              {},
            )
          : {},
    };
  },

  toJSON(message: ListResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.childrenFolders) {
      const entries = globalThis.Object.entries(message.childrenFolders) as [
        string,
        string,
      ][];
      if (entries.length > 0) {
        obj.childrenFolders = {};
        entries.forEach(([k, v]) => {
          obj.childrenFolders[k] = v;
        });
      }
    }
    if (message.childrenVars) {
      const entries = globalThis.Object.entries(message.childrenVars) as [
        string,
        VarInfo,
      ][];
      if (entries.length > 0) {
        obj.childrenVars = {};
        entries.forEach(([k, v]) => {
          obj.childrenVars[k] = VarInfo.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListResponse>, I>>(
    base?: I,
  ): ListResponse {
    return ListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListResponse>, I>>(
    object: I,
  ): ListResponse {
    const message = createBaseListResponse();
    message.cmdId = object.cmdId ?? "";
    message.childrenFolders = (
      globalThis.Object.entries(object.childrenFolders ?? {}) as [
        string,
        string,
      ][]
    ).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.childrenVars = (
      globalThis.Object.entries(object.childrenVars ?? {}) as [
        string,
        VarInfo,
      ][]
    ).reduce(
      (acc: { [key: string]: VarInfo }, [key, value]: [string, VarInfo]) => {
        if (value !== undefined) {
          acc[key] = VarInfo.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseListResponse_ChildrenFoldersEntry(): ListResponse_ChildrenFoldersEntry {
  return { key: "", value: "" };
}

export const ListResponse_ChildrenFoldersEntry: MessageFns<ListResponse_ChildrenFoldersEntry> =
  {
    encode(
      message: ListResponse_ChildrenFoldersEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.key !== "") {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== "") {
        writer.uint32(18).string(message.value);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): ListResponse_ChildrenFoldersEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListResponse_ChildrenFoldersEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): ListResponse_ChildrenFoldersEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : "",
        value: isSet(object.value) ? globalThis.String(object.value) : "",
      };
    },

    toJSON(message: ListResponse_ChildrenFoldersEntry): unknown {
      const obj: any = {};
      if (message.key !== "") {
        obj.key = message.key;
      }
      if (message.value !== "") {
        obj.value = message.value;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<ListResponse_ChildrenFoldersEntry>, I>>(
      base?: I,
    ): ListResponse_ChildrenFoldersEntry {
      return ListResponse_ChildrenFoldersEntry.fromPartial(base ?? ({} as any));
    },
    fromPartial<
      I extends Exact<DeepPartial<ListResponse_ChildrenFoldersEntry>, I>,
    >(object: I): ListResponse_ChildrenFoldersEntry {
      const message = createBaseListResponse_ChildrenFoldersEntry();
      message.key = object.key ?? "";
      message.value = object.value ?? "";
      return message;
    },
  };

function createBaseListResponse_ChildrenVarsEntry(): ListResponse_ChildrenVarsEntry {
  return { key: "", value: undefined };
}

export const ListResponse_ChildrenVarsEntry: MessageFns<ListResponse_ChildrenVarsEntry> =
  {
    encode(
      message: ListResponse_ChildrenVarsEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.key !== "") {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== undefined) {
        VarInfo.encode(message.value, writer.uint32(18).fork()).join();
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): ListResponse_ChildrenVarsEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListResponse_ChildrenVarsEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = VarInfo.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): ListResponse_ChildrenVarsEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : "",
        value: isSet(object.value) ? VarInfo.fromJSON(object.value) : undefined,
      };
    },

    toJSON(message: ListResponse_ChildrenVarsEntry): unknown {
      const obj: any = {};
      if (message.key !== "") {
        obj.key = message.key;
      }
      if (message.value !== undefined) {
        obj.value = VarInfo.toJSON(message.value);
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<ListResponse_ChildrenVarsEntry>, I>>(
      base?: I,
    ): ListResponse_ChildrenVarsEntry {
      return ListResponse_ChildrenVarsEntry.fromPartial(base ?? ({} as any));
    },
    fromPartial<
      I extends Exact<DeepPartial<ListResponse_ChildrenVarsEntry>, I>,
    >(object: I): ListResponse_ChildrenVarsEntry {
      const message = createBaseListResponse_ChildrenVarsEntry();
      message.key = object.key ?? "";
      message.value =
        object.value !== undefined && object.value !== null
          ? VarInfo.fromPartial(object.value)
          : undefined;
      return message;
    },
  };

function createBaseSetCommand(): SetCommand {
  return { cmdId: "", varIdsValues: [] };
}

export const SetCommand: MessageFns<SetCommand> = {
  encode(
    message: SetCommand,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varIdsValues) {
      VarIdValue.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetCommand {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varIdsValues.push(VarIdValue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      varIdsValues: globalThis.Array.isArray(object?.varIdsValues)
        ? object.varIdsValues.map((e: any) => VarIdValue.fromJSON(e))
        : globalThis.Array.isArray(object?.var_ids_values)
          ? object.var_ids_values.map((e: any) => VarIdValue.fromJSON(e))
          : [],
    };
  },

  toJSON(message: SetCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varIdsValues?.length) {
      obj.varIdsValues = message.varIdsValues.map((e) => VarIdValue.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetCommand>, I>>(base?: I): SetCommand {
    return SetCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetCommand>, I>>(
    object: I,
  ): SetCommand {
    const message = createBaseSetCommand();
    message.cmdId = object.cmdId ?? "";
    message.varIdsValues =
      object.varIdsValues?.map((e) => VarIdValue.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSetResponse(): SetResponse {
  return { cmdId: "" };
}

export const SetResponse: MessageFns<SetResponse> = {
  encode(
    message: SetResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
    };
  },

  toJSON(message: SetResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetResponse>, I>>(base?: I): SetResponse {
    return SetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetResponse>, I>>(
    object: I,
  ): SetResponse {
    const message = createBaseSetResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseGetCommand(): GetCommand {
  return { cmdId: "", varIds: [] };
}

export const GetCommand: MessageFns<GetCommand> = {
  encode(
    message: GetCommand,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCommand {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      varIds: globalThis.Array.isArray(object?.varIds)
        ? object.varIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.var_ids)
          ? object.var_ids.map((e: any) => globalThis.String(e))
          : [],
    };
  },

  toJSON(message: GetCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varIds?.length) {
      obj.varIds = message.varIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCommand>, I>>(base?: I): GetCommand {
    return GetCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCommand>, I>>(
    object: I,
  ): GetCommand {
    const message = createBaseGetCommand();
    message.cmdId = object.cmdId ?? "";
    message.varIds = object.varIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetResponse(): GetResponse {
  return { cmdId: "", varValues: [] };
}

export const GetResponse: MessageFns<GetResponse> = {
  encode(
    message: GetResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.varValues) {
      OptionalValue.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.varValues.push(OptionalValue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      varValues: globalThis.Array.isArray(object?.varValues)
        ? object.varValues.map((e: any) => OptionalValue.fromJSON(e))
        : globalThis.Array.isArray(object?.var_values)
          ? object.var_values.map((e: any) => OptionalValue.fromJSON(e))
          : [],
    };
  },

  toJSON(message: GetResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.varValues?.length) {
      obj.varValues = message.varValues.map((e) => OptionalValue.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetResponse>, I>>(base?: I): GetResponse {
    return GetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetResponse>, I>>(
    object: I,
  ): GetResponse {
    const message = createBaseGetResponse();
    message.cmdId = object.cmdId ?? "";
    message.varValues =
      object.varValues?.map((e) => OptionalValue.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDelCommand(): DelCommand {
  return { cmdId: "", itemIds: [] };
}

export const DelCommand: MessageFns<DelCommand> = {
  encode(
    message: DelCommand,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    for (const v of message.itemIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DelCommand {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDelCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.itemIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DelCommand {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
      itemIds: globalThis.Array.isArray(object?.itemIds)
        ? object.itemIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.item_ids)
          ? object.item_ids.map((e: any) => globalThis.String(e))
          : [],
    };
  },

  toJSON(message: DelCommand): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    if (message.itemIds?.length) {
      obj.itemIds = message.itemIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DelCommand>, I>>(base?: I): DelCommand {
    return DelCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DelCommand>, I>>(
    object: I,
  ): DelCommand {
    const message = createBaseDelCommand();
    message.cmdId = object.cmdId ?? "";
    message.itemIds = object.itemIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseDelResponse(): DelResponse {
  return { cmdId: "" };
}

export const DelResponse: MessageFns<DelResponse> = {
  encode(
    message: DelResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DelResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DelResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
    };
  },

  toJSON(message: DelResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DelResponse>, I>>(base?: I): DelResponse {
    return DelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DelResponse>, I>>(
    object: I,
  ): DelResponse {
    const message = createBaseDelResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseInvalidCmdResponse(): InvalidCmdResponse {
  return { cmdId: "" };
}

export const InvalidCmdResponse: MessageFns<InvalidCmdResponse> = {
  encode(
    message: InvalidCmdResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.cmdId !== "") {
      writer.uint32(10).string(message.cmdId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): InvalidCmdResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvalidCmdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InvalidCmdResponse {
    return {
      cmdId: isSet(object.cmdId)
        ? globalThis.String(object.cmdId)
        : isSet(object.cmd_id)
          ? globalThis.String(object.cmd_id)
          : "",
    };
  },

  toJSON(message: InvalidCmdResponse): unknown {
    const obj: any = {};
    if (message.cmdId !== "") {
      obj.cmdId = message.cmdId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvalidCmdResponse>, I>>(
    base?: I,
  ): InvalidCmdResponse {
    return InvalidCmdResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvalidCmdResponse>, I>>(
    object: I,
  ): InvalidCmdResponse {
    const message = createBaseInvalidCmdResponse();
    message.cmdId = object.cmdId ?? "";
    return message;
  },
};

function createBaseCommand(): Command {
  return {
    add: undefined,
    list: undefined,
    set: undefined,
    get: undefined,
    del: undefined,
    addBulk: undefined,
  };
}

export const Command: MessageFns<Command> = {
  encode(
    message: Command,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.add !== undefined) {
      AddCommand.encode(message.add, writer.uint32(10).fork()).join();
    }
    if (message.list !== undefined) {
      ListCommand.encode(message.list, writer.uint32(18).fork()).join();
    }
    if (message.set !== undefined) {
      SetCommand.encode(message.set, writer.uint32(26).fork()).join();
    }
    if (message.get !== undefined) {
      GetCommand.encode(message.get, writer.uint32(34).fork()).join();
    }
    if (message.del !== undefined) {
      DelCommand.encode(message.del, writer.uint32(42).fork()).join();
    }
    if (message.addBulk !== undefined) {
      AddBulkCommand.encode(message.addBulk, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Command {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.add = AddCommand.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.list = ListCommand.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.set = SetCommand.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.get = GetCommand.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.del = DelCommand.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.addBulk = AddBulkCommand.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Command {
    return {
      add: isSet(object.add) ? AddCommand.fromJSON(object.add) : undefined,
      list: isSet(object.list) ? ListCommand.fromJSON(object.list) : undefined,
      set: isSet(object.set) ? SetCommand.fromJSON(object.set) : undefined,
      get: isSet(object.get) ? GetCommand.fromJSON(object.get) : undefined,
      del: isSet(object.del) ? DelCommand.fromJSON(object.del) : undefined,
      addBulk: isSet(object.addBulk)
        ? AddBulkCommand.fromJSON(object.addBulk)
        : isSet(object.add_bulk)
          ? AddBulkCommand.fromJSON(object.add_bulk)
          : undefined,
    };
  },

  toJSON(message: Command): unknown {
    const obj: any = {};
    if (message.add !== undefined) {
      obj.add = AddCommand.toJSON(message.add);
    }
    if (message.list !== undefined) {
      obj.list = ListCommand.toJSON(message.list);
    }
    if (message.set !== undefined) {
      obj.set = SetCommand.toJSON(message.set);
    }
    if (message.get !== undefined) {
      obj.get = GetCommand.toJSON(message.get);
    }
    if (message.del !== undefined) {
      obj.del = DelCommand.toJSON(message.del);
    }
    if (message.addBulk !== undefined) {
      obj.addBulk = AddBulkCommand.toJSON(message.addBulk);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Command>, I>>(base?: I): Command {
    return Command.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Command>, I>>(object: I): Command {
    const message = createBaseCommand();
    message.add =
      object.add !== undefined && object.add !== null
        ? AddCommand.fromPartial(object.add)
        : undefined;
    message.list =
      object.list !== undefined && object.list !== null
        ? ListCommand.fromPartial(object.list)
        : undefined;
    message.set =
      object.set !== undefined && object.set !== null
        ? SetCommand.fromPartial(object.set)
        : undefined;
    message.get =
      object.get !== undefined && object.get !== null
        ? GetCommand.fromPartial(object.get)
        : undefined;
    message.del =
      object.del !== undefined && object.del !== null
        ? DelCommand.fromPartial(object.del)
        : undefined;
    message.addBulk =
      object.addBulk !== undefined && object.addBulk !== null
        ? AddBulkCommand.fromPartial(object.addBulk)
        : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    add: undefined,
    list: undefined,
    set: undefined,
    get: undefined,
    del: undefined,
    inv: undefined,
    addBulk: undefined,
    status: 0,
    errorMsg: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(
    message: Response,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.add !== undefined) {
      AddResponse.encode(message.add, writer.uint32(10).fork()).join();
    }
    if (message.list !== undefined) {
      ListResponse.encode(message.list, writer.uint32(18).fork()).join();
    }
    if (message.set !== undefined) {
      SetResponse.encode(message.set, writer.uint32(26).fork()).join();
    }
    if (message.get !== undefined) {
      GetResponse.encode(message.get, writer.uint32(34).fork()).join();
    }
    if (message.del !== undefined) {
      DelResponse.encode(message.del, writer.uint32(42).fork()).join();
    }
    if (message.inv !== undefined) {
      InvalidCmdResponse.encode(message.inv, writer.uint32(50).fork()).join();
    }
    if (message.addBulk !== undefined) {
      AddBulkResponse.encode(message.addBulk, writer.uint32(58).fork()).join();
    }
    if (message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.errorMsg !== undefined) {
      writer.uint32(74).string(message.errorMsg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.add = AddResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.list = ListResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.set = SetResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.get = GetResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.del = DelResponse.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.inv = InvalidCmdResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.addBulk = AddBulkResponse.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.errorMsg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      add: isSet(object.add) ? AddResponse.fromJSON(object.add) : undefined,
      list: isSet(object.list) ? ListResponse.fromJSON(object.list) : undefined,
      set: isSet(object.set) ? SetResponse.fromJSON(object.set) : undefined,
      get: isSet(object.get) ? GetResponse.fromJSON(object.get) : undefined,
      del: isSet(object.del) ? DelResponse.fromJSON(object.del) : undefined,
      inv: isSet(object.inv)
        ? InvalidCmdResponse.fromJSON(object.inv)
        : undefined,
      addBulk: isSet(object.addBulk)
        ? AddBulkResponse.fromJSON(object.addBulk)
        : isSet(object.add_bulk)
          ? AddBulkResponse.fromJSON(object.add_bulk)
          : undefined,
      status: isSet(object.status) ? operationStatusFromJSON(object.status) : 0,
      errorMsg: isSet(object.errorMsg)
        ? globalThis.String(object.errorMsg)
        : isSet(object.error_msg)
          ? globalThis.String(object.error_msg)
          : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.add !== undefined) {
      obj.add = AddResponse.toJSON(message.add);
    }
    if (message.list !== undefined) {
      obj.list = ListResponse.toJSON(message.list);
    }
    if (message.set !== undefined) {
      obj.set = SetResponse.toJSON(message.set);
    }
    if (message.get !== undefined) {
      obj.get = GetResponse.toJSON(message.get);
    }
    if (message.del !== undefined) {
      obj.del = DelResponse.toJSON(message.del);
    }
    if (message.inv !== undefined) {
      obj.inv = InvalidCmdResponse.toJSON(message.inv);
    }
    if (message.addBulk !== undefined) {
      obj.addBulk = AddBulkResponse.toJSON(message.addBulk);
    }
    if (message.status !== 0) {
      obj.status = operationStatusToJSON(message.status);
    }
    if (message.errorMsg !== undefined) {
      obj.errorMsg = message.errorMsg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.add =
      object.add !== undefined && object.add !== null
        ? AddResponse.fromPartial(object.add)
        : undefined;
    message.list =
      object.list !== undefined && object.list !== null
        ? ListResponse.fromPartial(object.list)
        : undefined;
    message.set =
      object.set !== undefined && object.set !== null
        ? SetResponse.fromPartial(object.set)
        : undefined;
    message.get =
      object.get !== undefined && object.get !== null
        ? GetResponse.fromPartial(object.get)
        : undefined;
    message.del =
      object.del !== undefined && object.del !== null
        ? DelResponse.fromPartial(object.del)
        : undefined;
    message.inv =
      object.inv !== undefined && object.inv !== null
        ? InvalidCmdResponse.fromPartial(object.inv)
        : undefined;
    message.addBulk =
      object.addBulk !== undefined && object.addBulk !== null
        ? AddBulkResponse.fromPartial(object.addBulk)
        : undefined;
    message.status = object.status ?? 0;
    message.errorMsg = object.errorMsg ?? undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
