// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: namespace/enums.proto

/* eslint-disable */

export const protobufPackage = "namespace";

/** ItemType */
export enum ItemType {
  ITEM_TYPE_INVALID = 0,
  ITEM_TYPE_FOLDER = 1,
  ITEM_TYPE_VARIABLE = 2,
  UNRECOGNIZED = -1,
}

export function itemTypeFromJSON(object: any): ItemType {
  switch (object) {
    case 0:
    case "ITEM_TYPE_INVALID":
      return ItemType.ITEM_TYPE_INVALID;
    case 1:
    case "ITEM_TYPE_FOLDER":
      return ItemType.ITEM_TYPE_FOLDER;
    case 2:
    case "ITEM_TYPE_VARIABLE":
      return ItemType.ITEM_TYPE_VARIABLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ItemType.UNRECOGNIZED;
  }
}

export function itemTypeToJSON(object: ItemType): string {
  switch (object) {
    case ItemType.ITEM_TYPE_INVALID:
      return "ITEM_TYPE_INVALID";
    case ItemType.ITEM_TYPE_FOLDER:
      return "ITEM_TYPE_FOLDER";
    case ItemType.ITEM_TYPE_VARIABLE:
      return "ITEM_TYPE_VARIABLE";
    case ItemType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** VarDataType */
export enum VarDataType {
  VAR_DATA_TYPE_INVALID = 0,
  VAR_DATA_TYPE_INTEGER = 1,
  VAR_DATA_TYPE_FLOAT = 2,
  VAR_DATA_TYPE_TEXT = 3,
  VAR_DATA_TYPE_BOOLEAN = 4,
  UNRECOGNIZED = -1,
}

export function varDataTypeFromJSON(object: any): VarDataType {
  switch (object) {
    case 0:
    case "VAR_DATA_TYPE_INVALID":
      return VarDataType.VAR_DATA_TYPE_INVALID;
    case 1:
    case "VAR_DATA_TYPE_INTEGER":
      return VarDataType.VAR_DATA_TYPE_INTEGER;
    case 2:
    case "VAR_DATA_TYPE_FLOAT":
      return VarDataType.VAR_DATA_TYPE_FLOAT;
    case 3:
    case "VAR_DATA_TYPE_TEXT":
      return VarDataType.VAR_DATA_TYPE_TEXT;
    case 4:
    case "VAR_DATA_TYPE_BOOLEAN":
      return VarDataType.VAR_DATA_TYPE_BOOLEAN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VarDataType.UNRECOGNIZED;
  }
}

export function varDataTypeToJSON(object: VarDataType): string {
  switch (object) {
    case VarDataType.VAR_DATA_TYPE_INVALID:
      return "VAR_DATA_TYPE_INVALID";
    case VarDataType.VAR_DATA_TYPE_INTEGER:
      return "VAR_DATA_TYPE_INTEGER";
    case VarDataType.VAR_DATA_TYPE_FLOAT:
      return "VAR_DATA_TYPE_FLOAT";
    case VarDataType.VAR_DATA_TYPE_TEXT:
      return "VAR_DATA_TYPE_TEXT";
    case VarDataType.VAR_DATA_TYPE_BOOLEAN:
      return "VAR_DATA_TYPE_BOOLEAN";
    case VarDataType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** OperationStatus */
export enum OperationStatus {
  OPERATION_STATUS_INVALID = 0,
  OPERATION_STATUS_OK = 1,
  OPERATION_STATUS_ERR = 2,
  UNRECOGNIZED = -1,
}

export function operationStatusFromJSON(object: any): OperationStatus {
  switch (object) {
    case 0:
    case "OPERATION_STATUS_INVALID":
      return OperationStatus.OPERATION_STATUS_INVALID;
    case 1:
    case "OPERATION_STATUS_OK":
      return OperationStatus.OPERATION_STATUS_OK;
    case 2:
    case "OPERATION_STATUS_ERR":
      return OperationStatus.OPERATION_STATUS_ERR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OperationStatus.UNRECOGNIZED;
  }
}

export function operationStatusToJSON(object: OperationStatus): string {
  switch (object) {
    case OperationStatus.OPERATION_STATUS_INVALID:
      return "OPERATION_STATUS_INVALID";
    case OperationStatus.OPERATION_STATUS_OK:
      return "OPERATION_STATUS_OK";
    case OperationStatus.OPERATION_STATUS_ERR:
      return "OPERATION_STATUS_ERR";
    case OperationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** EventType */
export enum EventType {
  EVENT_TYPE_INVALID = 0,
  EVENT_TYPE_TREE_CHANGE = 1,
  EVENT_TYPE_VAR_VALUES = 2,
  UNRECOGNIZED = -1,
}

export function eventTypeFromJSON(object: any): EventType {
  switch (object) {
    case 0:
    case "EVENT_TYPE_INVALID":
      return EventType.EVENT_TYPE_INVALID;
    case 1:
    case "EVENT_TYPE_TREE_CHANGE":
      return EventType.EVENT_TYPE_TREE_CHANGE;
    case 2:
    case "EVENT_TYPE_VAR_VALUES":
      return EventType.EVENT_TYPE_VAR_VALUES;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EventType.UNRECOGNIZED;
  }
}

export function eventTypeToJSON(object: EventType): string {
  switch (object) {
    case EventType.EVENT_TYPE_INVALID:
      return "EVENT_TYPE_INVALID";
    case EventType.EVENT_TYPE_TREE_CHANGE:
      return "EVENT_TYPE_TREE_CHANGE";
    case EventType.EVENT_TYPE_VAR_VALUES:
      return "EVENT_TYPE_VAR_VALUES";
    case EventType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
