// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: namespace/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "namespace";

export interface ItemsCreatedEvent {
  foldersToReload: string[];
  newItems: string[];
}

export interface ItemsDeletedEvent {
  /** 16 bytes */
  rootUid: string;
  vendor: string;
}

export interface Event {
  createdEv?: ItemsCreatedEvent | undefined;
  deletedEv?: ItemsCreatedEvent | undefined;
}

function createBaseItemsCreatedEvent(): ItemsCreatedEvent {
  return { foldersToReload: [], newItems: [] };
}

export const ItemsCreatedEvent: MessageFns<ItemsCreatedEvent> = {
  encode(message: ItemsCreatedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.foldersToReload) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.newItems) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemsCreatedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemsCreatedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.foldersToReload.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.newItems.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemsCreatedEvent {
    return {
      foldersToReload: globalThis.Array.isArray(object?.foldersToReload)
        ? object.foldersToReload.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.folders_to_reload)
        ? object.folders_to_reload.map((e: any) => globalThis.String(e))
        : [],
      newItems: globalThis.Array.isArray(object?.newItems)
        ? object.newItems.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.new_items)
        ? object.new_items.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ItemsCreatedEvent): unknown {
    const obj: any = {};
    if (message.foldersToReload?.length) {
      obj.foldersToReload = message.foldersToReload;
    }
    if (message.newItems?.length) {
      obj.newItems = message.newItems;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemsCreatedEvent>, I>>(base?: I): ItemsCreatedEvent {
    return ItemsCreatedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemsCreatedEvent>, I>>(object: I): ItemsCreatedEvent {
    const message = createBaseItemsCreatedEvent();
    message.foldersToReload = object.foldersToReload?.map((e) => e) || [];
    message.newItems = object.newItems?.map((e) => e) || [];
    return message;
  },
};

function createBaseItemsDeletedEvent(): ItemsDeletedEvent {
  return { rootUid: "", vendor: "" };
}

export const ItemsDeletedEvent: MessageFns<ItemsDeletedEvent> = {
  encode(message: ItemsDeletedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rootUid !== "") {
      writer.uint32(10).string(message.rootUid);
    }
    if (message.vendor !== "") {
      writer.uint32(18).string(message.vendor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemsDeletedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemsDeletedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rootUid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.vendor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemsDeletedEvent {
    return {
      rootUid: isSet(object.rootUid)
        ? globalThis.String(object.rootUid)
        : isSet(object.root_uid)
        ? globalThis.String(object.root_uid)
        : "",
      vendor: isSet(object.vendor) ? globalThis.String(object.vendor) : "",
    };
  },

  toJSON(message: ItemsDeletedEvent): unknown {
    const obj: any = {};
    if (message.rootUid !== "") {
      obj.rootUid = message.rootUid;
    }
    if (message.vendor !== "") {
      obj.vendor = message.vendor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemsDeletedEvent>, I>>(base?: I): ItemsDeletedEvent {
    return ItemsDeletedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemsDeletedEvent>, I>>(object: I): ItemsDeletedEvent {
    const message = createBaseItemsDeletedEvent();
    message.rootUid = object.rootUid ?? "";
    message.vendor = object.vendor ?? "";
    return message;
  },
};

function createBaseEvent(): Event {
  return { createdEv: undefined, deletedEv: undefined };
}

export const Event: MessageFns<Event> = {
  encode(message: Event, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.createdEv !== undefined) {
      ItemsCreatedEvent.encode(message.createdEv, writer.uint32(10).fork()).join();
    }
    if (message.deletedEv !== undefined) {
      ItemsCreatedEvent.encode(message.deletedEv, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Event {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.createdEv = ItemsCreatedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deletedEv = ItemsCreatedEvent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Event {
    return {
      createdEv: isSet(object.createdEv)
        ? ItemsCreatedEvent.fromJSON(object.createdEv)
        : isSet(object.created_ev)
        ? ItemsCreatedEvent.fromJSON(object.created_ev)
        : undefined,
      deletedEv: isSet(object.deletedEv)
        ? ItemsCreatedEvent.fromJSON(object.deletedEv)
        : isSet(object.deleted_ev)
        ? ItemsCreatedEvent.fromJSON(object.deleted_ev)
        : undefined,
    };
  },

  toJSON(message: Event): unknown {
    const obj: any = {};
    if (message.createdEv !== undefined) {
      obj.createdEv = ItemsCreatedEvent.toJSON(message.createdEv);
    }
    if (message.deletedEv !== undefined) {
      obj.deletedEv = ItemsCreatedEvent.toJSON(message.deletedEv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Event>, I>>(base?: I): Event {
    return Event.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Event>, I>>(object: I): Event {
    const message = createBaseEvent();
    message.createdEv = (object.createdEv !== undefined && object.createdEv !== null)
      ? ItemsCreatedEvent.fromPartial(object.createdEv)
      : undefined;
    message.deletedEv = (object.deletedEv !== undefined && object.deletedEv !== null)
      ? ItemsCreatedEvent.fromPartial(object.deletedEv)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
