// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: namespace/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FolderInfo, VarIdValue, VarInfo } from "./types";

export const protobufPackage = "namespace";

export interface FolderChanged {
  folderId: string;
  reload: boolean;
  removedItems: string[];
  newFolders: FolderInfo[];
  newVariables: VarInfo[];
}

export interface TreeChanged {
  folderChangedEvent: FolderChanged[];
}

export interface Event {
  varValueEv?: VarIdValue | undefined;
  treeChangedEv?: TreeChanged | undefined;
}

function createBaseFolderChanged(): FolderChanged {
  return { folderId: "", reload: false, removedItems: [], newFolders: [], newVariables: [] };
}

export const FolderChanged: MessageFns<FolderChanged> = {
  encode(message: FolderChanged, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.folderId !== "") {
      writer.uint32(10).string(message.folderId);
    }
    if (message.reload !== false) {
      writer.uint32(16).bool(message.reload);
    }
    for (const v of message.removedItems) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.newFolders) {
      FolderInfo.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.newVariables) {
      VarInfo.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FolderChanged {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFolderChanged();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.reload = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.removedItems.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.newFolders.push(FolderInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.newVariables.push(VarInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FolderChanged {
    return {
      folderId: isSet(object.folderId)
        ? globalThis.String(object.folderId)
        : isSet(object.folder_id)
        ? globalThis.String(object.folder_id)
        : "",
      reload: isSet(object.reload) ? globalThis.Boolean(object.reload) : false,
      removedItems: globalThis.Array.isArray(object?.removedItems)
        ? object.removedItems.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.removed_items)
        ? object.removed_items.map((e: any) => globalThis.String(e))
        : [],
      newFolders: globalThis.Array.isArray(object?.newFolders)
        ? object.newFolders.map((e: any) => FolderInfo.fromJSON(e))
        : globalThis.Array.isArray(object?.new_folders)
        ? object.new_folders.map((e: any) => FolderInfo.fromJSON(e))
        : [],
      newVariables: globalThis.Array.isArray(object?.newVariables)
        ? object.newVariables.map((e: any) => VarInfo.fromJSON(e))
        : globalThis.Array.isArray(object?.new_variables)
        ? object.new_variables.map((e: any) => VarInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FolderChanged): unknown {
    const obj: any = {};
    if (message.folderId !== "") {
      obj.folderId = message.folderId;
    }
    if (message.reload !== false) {
      obj.reload = message.reload;
    }
    if (message.removedItems?.length) {
      obj.removedItems = message.removedItems;
    }
    if (message.newFolders?.length) {
      obj.newFolders = message.newFolders.map((e) => FolderInfo.toJSON(e));
    }
    if (message.newVariables?.length) {
      obj.newVariables = message.newVariables.map((e) => VarInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FolderChanged>, I>>(base?: I): FolderChanged {
    return FolderChanged.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FolderChanged>, I>>(object: I): FolderChanged {
    const message = createBaseFolderChanged();
    message.folderId = object.folderId ?? "";
    message.reload = object.reload ?? false;
    message.removedItems = object.removedItems?.map((e) => e) || [];
    message.newFolders = object.newFolders?.map((e) => FolderInfo.fromPartial(e)) || [];
    message.newVariables = object.newVariables?.map((e) => VarInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTreeChanged(): TreeChanged {
  return { folderChangedEvent: [] };
}

export const TreeChanged: MessageFns<TreeChanged> = {
  encode(message: TreeChanged, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.folderChangedEvent) {
      FolderChanged.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TreeChanged {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTreeChanged();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folderChangedEvent.push(FolderChanged.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TreeChanged {
    return {
      folderChangedEvent: globalThis.Array.isArray(object?.folderChangedEvent)
        ? object.folderChangedEvent.map((e: any) => FolderChanged.fromJSON(e))
        : globalThis.Array.isArray(object?.folder_changed_event)
        ? object.folder_changed_event.map((e: any) => FolderChanged.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TreeChanged): unknown {
    const obj: any = {};
    if (message.folderChangedEvent?.length) {
      obj.folderChangedEvent = message.folderChangedEvent.map((e) => FolderChanged.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TreeChanged>, I>>(base?: I): TreeChanged {
    return TreeChanged.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TreeChanged>, I>>(object: I): TreeChanged {
    const message = createBaseTreeChanged();
    message.folderChangedEvent = object.folderChangedEvent?.map((e) => FolderChanged.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEvent(): Event {
  return { varValueEv: undefined, treeChangedEv: undefined };
}

export const Event: MessageFns<Event> = {
  encode(message: Event, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.varValueEv !== undefined) {
      VarIdValue.encode(message.varValueEv, writer.uint32(10).fork()).join();
    }
    if (message.treeChangedEv !== undefined) {
      TreeChanged.encode(message.treeChangedEv, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Event {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.varValueEv = VarIdValue.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.treeChangedEv = TreeChanged.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Event {
    return {
      varValueEv: isSet(object.varValueEv)
        ? VarIdValue.fromJSON(object.varValueEv)
        : isSet(object.var_value_ev)
        ? VarIdValue.fromJSON(object.var_value_ev)
        : undefined,
      treeChangedEv: isSet(object.treeChangedEv)
        ? TreeChanged.fromJSON(object.treeChangedEv)
        : isSet(object.tree_changed_ev)
        ? TreeChanged.fromJSON(object.tree_changed_ev)
        : undefined,
    };
  },

  toJSON(message: Event): unknown {
    const obj: any = {};
    if (message.varValueEv !== undefined) {
      obj.varValueEv = VarIdValue.toJSON(message.varValueEv);
    }
    if (message.treeChangedEv !== undefined) {
      obj.treeChangedEv = TreeChanged.toJSON(message.treeChangedEv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Event>, I>>(base?: I): Event {
    return Event.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Event>, I>>(object: I): Event {
    const message = createBaseEvent();
    message.varValueEv = (object.varValueEv !== undefined && object.varValueEv !== null)
      ? VarIdValue.fromPartial(object.varValueEv)
      : undefined;
    message.treeChangedEv = (object.treeChangedEv !== undefined && object.treeChangedEv !== null)
      ? TreeChanged.fromPartial(object.treeChangedEv)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
