// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: namespace/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  ItemType,
  itemTypeFromJSON,
  itemTypeToJSON,
  VarDataType,
  varDataTypeFromJSON,
  varDataTypeToJSON,
} from "./enums";

export const protobufPackage = "namespace";

export interface Value {
  integerValue?: number | undefined;
  floatValue?: number | undefined;
  textValue?: string | undefined;
  booleanValue?: boolean | undefined;
}

/**
 * Protobuf repeated fields cannot directly contain optional messages
 * without a wrapper.
 */
export interface OptionalValue {
  /** If this field is not set, it implies None */
  value: Value | undefined;
}

export interface ChildInfo {
  childId: string;
  iType: ItemType;
  varDType?: VarDataType | undefined;
}

export interface ItemMeta {
  name: string;
  iType: ItemType;
  varDType?: VarDataType | undefined;
}

export interface FolderInfo {
  id: string;
  name: string;
}

export interface VarInfo {
  id: string;
  name: string;
  varDType: VarDataType;
}

export interface VarIdValue {
  varId: string;
  value: Value | undefined;
}

export interface NamespaceSchema {
  roots: { [key: string]: NamespaceNode };
}

export interface NamespaceSchema_RootsEntry {
  key: string;
  value: NamespaceNode | undefined;
}

export interface NamespaceNode {
  folder?: NamespaceFolder | undefined;
  variableType?: string | undefined;
}

export interface NamespaceFolder {
  children: { [key: string]: NamespaceNode };
}

export interface NamespaceFolder_ChildrenEntry {
  key: string;
  value: NamespaceNode | undefined;
}

function createBaseValue(): Value {
  return { integerValue: undefined, floatValue: undefined, textValue: undefined, booleanValue: undefined };
}

export const Value: MessageFns<Value> = {
  encode(message: Value, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.integerValue !== undefined) {
      writer.uint32(8).int64(message.integerValue);
    }
    if (message.floatValue !== undefined) {
      writer.uint32(17).double(message.floatValue);
    }
    if (message.textValue !== undefined) {
      writer.uint32(26).string(message.textValue);
    }
    if (message.booleanValue !== undefined) {
      writer.uint32(32).bool(message.booleanValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Value {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.integerValue = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.floatValue = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.textValue = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.booleanValue = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Value {
    return {
      integerValue: isSet(object.integerValue)
        ? globalThis.Number(object.integerValue)
        : isSet(object.integer_value)
        ? globalThis.Number(object.integer_value)
        : undefined,
      floatValue: isSet(object.floatValue)
        ? globalThis.Number(object.floatValue)
        : isSet(object.float_value)
        ? globalThis.Number(object.float_value)
        : undefined,
      textValue: isSet(object.textValue)
        ? globalThis.String(object.textValue)
        : isSet(object.text_value)
        ? globalThis.String(object.text_value)
        : undefined,
      booleanValue: isSet(object.booleanValue)
        ? globalThis.Boolean(object.booleanValue)
        : isSet(object.boolean_value)
        ? globalThis.Boolean(object.boolean_value)
        : undefined,
    };
  },

  toJSON(message: Value): unknown {
    const obj: any = {};
    if (message.integerValue !== undefined) {
      obj.integerValue = Math.round(message.integerValue);
    }
    if (message.floatValue !== undefined) {
      obj.floatValue = message.floatValue;
    }
    if (message.textValue !== undefined) {
      obj.textValue = message.textValue;
    }
    if (message.booleanValue !== undefined) {
      obj.booleanValue = message.booleanValue;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Value>, I>>(base?: I): Value {
    return Value.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Value>, I>>(object: I): Value {
    const message = createBaseValue();
    message.integerValue = object.integerValue ?? undefined;
    message.floatValue = object.floatValue ?? undefined;
    message.textValue = object.textValue ?? undefined;
    message.booleanValue = object.booleanValue ?? undefined;
    return message;
  },
};

function createBaseOptionalValue(): OptionalValue {
  return { value: undefined };
}

export const OptionalValue: MessageFns<OptionalValue> = {
  encode(message: OptionalValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== undefined) {
      Value.encode(message.value, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionalValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionalValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = Value.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OptionalValue {
    return { value: isSet(object.value) ? Value.fromJSON(object.value) : undefined };
  },

  toJSON(message: OptionalValue): unknown {
    const obj: any = {};
    if (message.value !== undefined) {
      obj.value = Value.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OptionalValue>, I>>(base?: I): OptionalValue {
    return OptionalValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OptionalValue>, I>>(object: I): OptionalValue {
    const message = createBaseOptionalValue();
    message.value = (object.value !== undefined && object.value !== null) ? Value.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseChildInfo(): ChildInfo {
  return { childId: "", iType: 0, varDType: undefined };
}

export const ChildInfo: MessageFns<ChildInfo> = {
  encode(message: ChildInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.childId !== "") {
      writer.uint32(10).string(message.childId);
    }
    if (message.iType !== 0) {
      writer.uint32(16).int32(message.iType);
    }
    if (message.varDType !== undefined) {
      writer.uint32(24).int32(message.varDType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChildInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChildInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.childId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.iType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.varDType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChildInfo {
    return {
      childId: isSet(object.childId)
        ? globalThis.String(object.childId)
        : isSet(object.child_id)
        ? globalThis.String(object.child_id)
        : "",
      iType: isSet(object.iType)
        ? itemTypeFromJSON(object.iType)
        : isSet(object.i_type)
        ? itemTypeFromJSON(object.i_type)
        : 0,
      varDType: isSet(object.varDType)
        ? varDataTypeFromJSON(object.varDType)
        : isSet(object.var_d_type)
        ? varDataTypeFromJSON(object.var_d_type)
        : undefined,
    };
  },

  toJSON(message: ChildInfo): unknown {
    const obj: any = {};
    if (message.childId !== "") {
      obj.childId = message.childId;
    }
    if (message.iType !== 0) {
      obj.iType = itemTypeToJSON(message.iType);
    }
    if (message.varDType !== undefined) {
      obj.varDType = varDataTypeToJSON(message.varDType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChildInfo>, I>>(base?: I): ChildInfo {
    return ChildInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChildInfo>, I>>(object: I): ChildInfo {
    const message = createBaseChildInfo();
    message.childId = object.childId ?? "";
    message.iType = object.iType ?? 0;
    message.varDType = object.varDType ?? undefined;
    return message;
  },
};

function createBaseItemMeta(): ItemMeta {
  return { name: "", iType: 0, varDType: undefined };
}

export const ItemMeta: MessageFns<ItemMeta> = {
  encode(message: ItemMeta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.iType !== 0) {
      writer.uint32(16).int32(message.iType);
    }
    if (message.varDType !== undefined) {
      writer.uint32(24).int32(message.varDType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemMeta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemMeta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.iType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.varDType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemMeta {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      iType: isSet(object.iType)
        ? itemTypeFromJSON(object.iType)
        : isSet(object.i_type)
        ? itemTypeFromJSON(object.i_type)
        : 0,
      varDType: isSet(object.varDType)
        ? varDataTypeFromJSON(object.varDType)
        : isSet(object.var_d_type)
        ? varDataTypeFromJSON(object.var_d_type)
        : undefined,
    };
  },

  toJSON(message: ItemMeta): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.iType !== 0) {
      obj.iType = itemTypeToJSON(message.iType);
    }
    if (message.varDType !== undefined) {
      obj.varDType = varDataTypeToJSON(message.varDType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemMeta>, I>>(base?: I): ItemMeta {
    return ItemMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemMeta>, I>>(object: I): ItemMeta {
    const message = createBaseItemMeta();
    message.name = object.name ?? "";
    message.iType = object.iType ?? 0;
    message.varDType = object.varDType ?? undefined;
    return message;
  },
};

function createBaseFolderInfo(): FolderInfo {
  return { id: "", name: "" };
}

export const FolderInfo: MessageFns<FolderInfo> = {
  encode(message: FolderInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FolderInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFolderInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FolderInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: FolderInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FolderInfo>, I>>(base?: I): FolderInfo {
    return FolderInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FolderInfo>, I>>(object: I): FolderInfo {
    const message = createBaseFolderInfo();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseVarInfo(): VarInfo {
  return { id: "", name: "", varDType: 0 };
}

export const VarInfo: MessageFns<VarInfo> = {
  encode(message: VarInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.varDType !== 0) {
      writer.uint32(24).int32(message.varDType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VarInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVarInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.varDType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VarInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      varDType: isSet(object.varDType)
        ? varDataTypeFromJSON(object.varDType)
        : isSet(object.var_d_type)
        ? varDataTypeFromJSON(object.var_d_type)
        : 0,
    };
  },

  toJSON(message: VarInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.varDType !== 0) {
      obj.varDType = varDataTypeToJSON(message.varDType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VarInfo>, I>>(base?: I): VarInfo {
    return VarInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VarInfo>, I>>(object: I): VarInfo {
    const message = createBaseVarInfo();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.varDType = object.varDType ?? 0;
    return message;
  },
};

function createBaseVarIdValue(): VarIdValue {
  return { varId: "", value: undefined };
}

export const VarIdValue: MessageFns<VarIdValue> = {
  encode(message: VarIdValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.varId !== "") {
      writer.uint32(10).string(message.varId);
    }
    if (message.value !== undefined) {
      Value.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VarIdValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVarIdValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.varId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Value.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VarIdValue {
    return {
      varId: isSet(object.varId)
        ? globalThis.String(object.varId)
        : isSet(object.var_id)
        ? globalThis.String(object.var_id)
        : "",
      value: isSet(object.value) ? Value.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: VarIdValue): unknown {
    const obj: any = {};
    if (message.varId !== "") {
      obj.varId = message.varId;
    }
    if (message.value !== undefined) {
      obj.value = Value.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VarIdValue>, I>>(base?: I): VarIdValue {
    return VarIdValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VarIdValue>, I>>(object: I): VarIdValue {
    const message = createBaseVarIdValue();
    message.varId = object.varId ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Value.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseNamespaceSchema(): NamespaceSchema {
  return { roots: {} };
}

export const NamespaceSchema: MessageFns<NamespaceSchema> = {
  encode(message: NamespaceSchema, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.roots).forEach(([key, value]: [string, NamespaceNode]) => {
      NamespaceSchema_RootsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NamespaceSchema {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamespaceSchema();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = NamespaceSchema_RootsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.roots[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NamespaceSchema {
    return {
      roots: isObject(object.roots)
        ? (globalThis.Object.entries(object.roots) as [string, any][]).reduce(
          (acc: { [key: string]: NamespaceNode }, [key, value]: [string, any]) => {
            acc[key] = NamespaceNode.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: NamespaceSchema): unknown {
    const obj: any = {};
    if (message.roots) {
      const entries = globalThis.Object.entries(message.roots) as [string, NamespaceNode][];
      if (entries.length > 0) {
        obj.roots = {};
        entries.forEach(([k, v]) => {
          obj.roots[k] = NamespaceNode.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamespaceSchema>, I>>(base?: I): NamespaceSchema {
    return NamespaceSchema.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamespaceSchema>, I>>(object: I): NamespaceSchema {
    const message = createBaseNamespaceSchema();
    message.roots = (globalThis.Object.entries(object.roots ?? {}) as [string, NamespaceNode][]).reduce(
      (acc: { [key: string]: NamespaceNode }, [key, value]: [string, NamespaceNode]) => {
        if (value !== undefined) {
          acc[key] = NamespaceNode.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseNamespaceSchema_RootsEntry(): NamespaceSchema_RootsEntry {
  return { key: "", value: undefined };
}

export const NamespaceSchema_RootsEntry: MessageFns<NamespaceSchema_RootsEntry> = {
  encode(message: NamespaceSchema_RootsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      NamespaceNode.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NamespaceSchema_RootsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamespaceSchema_RootsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = NamespaceNode.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NamespaceSchema_RootsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? NamespaceNode.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: NamespaceSchema_RootsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = NamespaceNode.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamespaceSchema_RootsEntry>, I>>(base?: I): NamespaceSchema_RootsEntry {
    return NamespaceSchema_RootsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamespaceSchema_RootsEntry>, I>>(object: I): NamespaceSchema_RootsEntry {
    const message = createBaseNamespaceSchema_RootsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? NamespaceNode.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseNamespaceNode(): NamespaceNode {
  return { folder: undefined, variableType: undefined };
}

export const NamespaceNode: MessageFns<NamespaceNode> = {
  encode(message: NamespaceNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.folder !== undefined) {
      NamespaceFolder.encode(message.folder, writer.uint32(10).fork()).join();
    }
    if (message.variableType !== undefined) {
      writer.uint32(18).string(message.variableType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NamespaceNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamespaceNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.folder = NamespaceFolder.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.variableType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NamespaceNode {
    return {
      folder: isSet(object.folder) ? NamespaceFolder.fromJSON(object.folder) : undefined,
      variableType: isSet(object.variableType)
        ? globalThis.String(object.variableType)
        : isSet(object.variable_type)
        ? globalThis.String(object.variable_type)
        : undefined,
    };
  },

  toJSON(message: NamespaceNode): unknown {
    const obj: any = {};
    if (message.folder !== undefined) {
      obj.folder = NamespaceFolder.toJSON(message.folder);
    }
    if (message.variableType !== undefined) {
      obj.variableType = message.variableType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamespaceNode>, I>>(base?: I): NamespaceNode {
    return NamespaceNode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamespaceNode>, I>>(object: I): NamespaceNode {
    const message = createBaseNamespaceNode();
    message.folder = (object.folder !== undefined && object.folder !== null)
      ? NamespaceFolder.fromPartial(object.folder)
      : undefined;
    message.variableType = object.variableType ?? undefined;
    return message;
  },
};

function createBaseNamespaceFolder(): NamespaceFolder {
  return { children: {} };
}

export const NamespaceFolder: MessageFns<NamespaceFolder> = {
  encode(message: NamespaceFolder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.children).forEach(([key, value]: [string, NamespaceNode]) => {
      NamespaceFolder_ChildrenEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NamespaceFolder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamespaceFolder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = NamespaceFolder_ChildrenEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.children[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NamespaceFolder {
    return {
      children: isObject(object.children)
        ? (globalThis.Object.entries(object.children) as [string, any][]).reduce(
          (acc: { [key: string]: NamespaceNode }, [key, value]: [string, any]) => {
            acc[key] = NamespaceNode.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: NamespaceFolder): unknown {
    const obj: any = {};
    if (message.children) {
      const entries = globalThis.Object.entries(message.children) as [string, NamespaceNode][];
      if (entries.length > 0) {
        obj.children = {};
        entries.forEach(([k, v]) => {
          obj.children[k] = NamespaceNode.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamespaceFolder>, I>>(base?: I): NamespaceFolder {
    return NamespaceFolder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamespaceFolder>, I>>(object: I): NamespaceFolder {
    const message = createBaseNamespaceFolder();
    message.children = (globalThis.Object.entries(object.children ?? {}) as [string, NamespaceNode][]).reduce(
      (acc: { [key: string]: NamespaceNode }, [key, value]: [string, NamespaceNode]) => {
        if (value !== undefined) {
          acc[key] = NamespaceNode.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseNamespaceFolder_ChildrenEntry(): NamespaceFolder_ChildrenEntry {
  return { key: "", value: undefined };
}

export const NamespaceFolder_ChildrenEntry: MessageFns<NamespaceFolder_ChildrenEntry> = {
  encode(message: NamespaceFolder_ChildrenEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      NamespaceNode.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NamespaceFolder_ChildrenEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamespaceFolder_ChildrenEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = NamespaceNode.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NamespaceFolder_ChildrenEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? NamespaceNode.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: NamespaceFolder_ChildrenEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = NamespaceNode.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamespaceFolder_ChildrenEntry>, I>>(base?: I): NamespaceFolder_ChildrenEntry {
    return NamespaceFolder_ChildrenEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamespaceFolder_ChildrenEntry>, I>>(
    object: I,
  ): NamespaceFolder_ChildrenEntry {
    const message = createBaseNamespaceFolder_ChildrenEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? NamespaceNode.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
