# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: namespace/events.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'namespace/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import enums_pb2 as namespace_dot_enums__pb2
from . import types_pb2 as namespace_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16namespace/events.proto\x12\tnamespace\x1a\x15namespace/enums.proto\x1a\x15namespace/types.proto\"\xa0\x01\n\rFolderChanged\x12\x11\n\tfolder_id\x18\x01 \x01(\t\x12\x0e\n\x06reload\x18\x02 \x01(\x08\x12\x15\n\rremoved_items\x18\x03 \x03(\t\x12*\n\x0bnew_folders\x18\x04 \x03(\x0b\x32\x15.namespace.FolderInfo\x12)\n\rnew_variables\x18\x05 \x03(\x0b\x32\x12.namespace.VarInfo\"E\n\x0bTreeChanged\x12\x36\n\x14\x66older_changed_event\x18\x01 \x03(\x0b\x32\x18.namespace.FolderChanged\"o\n\x05\x45vent\x12-\n\x0cvar_value_ev\x18\x01 \x01(\x0b\x32\x15.namespace.VarIdValueH\x00\x12\x31\n\x0ftree_changed_ev\x18\x02 \x01(\x0b\x32\x16.namespace.TreeChangedH\x00\x42\x04\n\x02\x65vb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'namespace.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLDERCHANGED']._serialized_start=84
  _globals['_FOLDERCHANGED']._serialized_end=244
  _globals['_TREECHANGED']._serialized_start=246
  _globals['_TREECHANGED']._serialized_end=315
  _globals['_EVENT']._serialized_start=317
  _globals['_EVENT']._serialized_end=428
# @@protoc_insertion_point(module_scope)
